#!/usr/bin/env bash
FILE="$(readlink -f "$0")"
DIR="$(dirname "$FILE")"
CACHE_DIR="$DIR/.cache"
VENV_ACTIVATE="$CACHE_DIR/bin/activate"
VENV_PYTHON="$CACHE_DIR/bin/python"

# Ensure Python virtual environment is present and activated
if [ ! -f "$VENV_ACTIVATE" ]; then
    python3 -m venv "$CACHE_DIR" --without-pip
    source "$VENV_ACTIVATE"
    # Use "get-pip" to handle cases where "ensurepip" is missing
    curl https://bootstrap.pypa.io/get-pip.py -sSL | "$VENV_PYTHON" 1>/dev/null
else
    source "$VENV_ACTIVATE"
fi

# Ensure user executable link is present
mkdir -p ~/.local/bin
ln -sfr "$FILE" ~/.local/bin/acid

# Run command in the Python virtual environment
PYTHONPATH=$DIR "$VENV_PYTHON" "$DIR/__main__.py" "${@}"
exit $?
