---
# Start an AWS EC2 instance to run and agent

parameters:
  # Job name to use
  jobName: startAgent
  # Agent description
  agentDescription: AWS EC2
  # Agent instance provider
  provider: awsEc2
  # Agent instance type
  # - awsEc2: EC2 instance type
  instanceType: f1.2xlarge
  # Image name to use
  image: centos_7
  # Path to "acid" directory
  acidDir: $(Build.SourcesDirectory)/acid
  # Path to Ansible "playbook.yml" file. Default to a playbook that only start
  # the agent.
  ansiblePlaybook: $(acidPath.acidDir)/agents/playbook.yml
  # Agent shutdown timeout in minute
  timeout: 60
  # Use spot instance
  spot: true
  # Jobs dependencies
  dependsOn: []
  # Agent Pool name
  agentPool: Default
  # Job condition
  condition: succeeded()

jobs:
  - job: ${{ parameters.jobName }}
    displayName: Start ${{ parameters.agentDescription }} agent
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    variables:
      - group: agentManager
      - name: terraformWorkingDir
        value: $(acidPath.acidDir)/agents/${{ parameters.provider }}
      - name: agentName
        value: $(Build.BuildId) $(Build.DefinitionName) ${{ parameters.agentDescription }}
      - name: ansibleRolePath
        value: "~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:\
                $(acidPath.acidDir)/.cache/lib/ansible/roles:\
                $(acidPath.acidDir)/roles"

    steps:

      - checkout: self
        submodules: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
        displayName: Get Python

      - task: PythonScript@0
        displayName: Autodetect Acid path
        name: acidPath
        inputs:
          scriptSource: inline
          script: |
            from os.path import isdir, dirname, join
            for path in {"$(Agent.BuildDirectory)/s",
                         "$(Agent.BuildDirectory)/s/acid",
                         "${{ parameters.acidDir }}"}:
                print(f'Searching in path: "{path}"')
                if isdir(join(path, "agents/awsEc2")):
                    print('Detected Acid path:', path)
                    break
            else:
                raise RuntimeError('Unable to find "acid" directory')

            import sys
            sys.path.append(path)

            from __init__ import export
            export('acidDir', path)

      - task: PythonScript@0
        displayName: Initialize Ansible
        inputs:
          scriptSource: inline
          script: |
            import sys
            sys.path.append("$(acidPath.acidDir)")
            from __init__ import ensure_ansible_roles
            ensure_ansible_roles("${{ parameters.ansiblePlaybook }}")

      - script: terraform init -input=false
        displayName: Initialize Terraform plugins
        workingDirectory: $(terraformWorkingDir)

      - task: PythonScript@0
        displayName: Initialize Terraform variables
        inputs:
          scriptSource: inline
          script: |
            import sys
            sys.path.append("$(acidPath.acidDir)")
            from __init__ import dump_tfvars, define_unique_name
            dump_tfvars(
              "$(terraformWorkingDir)",
              name="AzurePipeline" + define_unique_name(
                  "$(System.TeamProject)",
                  "$(Build.Repository.Name)",
                  "$(Build.SourceBranchName)",
                  "$(Build.BuildId)"),
              image="${{ parameters.image }}",
              playbook="${{ parameters.ansiblePlaybook }}")
            print('Agent Name: $(agentName)')

      - ${{ if eq(parameters.provider, 'awsEc2') }}:
        - task: PythonScript@0
          displayName: Initialize AWS EC2 specific Terraform variables
          inputs:
            scriptSource: inline
            script: |
              import sys
              sys.path.append("$(acidPath.acidDir)")
              from __init__ import dump_tfvars
              dump_tfvars(
                "$(terraformWorkingDir)",
                instance_type="${{ parameters.instanceType }}",
                spot="${{ parameters.spot }}")

        - task: AWSShellScript@1
          displayName: Start agent AWS EC2 instance
          inputs:
            awsCredentials: AWS
            regionName: eu-west-1
            scriptType: inline
            inlineScript: python apply_with_spot_retries.py
            disableAutoCwd: true
            workingDirectory: $(terraformWorkingDir)
          env:
            AZURE_AGENT_TOKEN: $(agentManagerToken)
            AZURE_AGENT_SHUTDOWN_TIMEOUT: ${{ parameters.timeout }}
            AZURE_AGENT_NAME: $(agentName)
            AZURE_AGENT_URL: $(System.TeamFoundationCollectionUri)
            AZURE_AGENT_POOL: ${{ parameters.agentPool }}
            ANSIBLE_ROLES_PATH: $(ansibleRolePath)

      - publish: $(terraformWorkingDir)
        artifact: Terraform State ${{ parameters.agentDescription }}
        displayName: Publish Terraform state
        condition: always()
